name: build-and-deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./src/SoftCraft.HttpApi.Host/SoftCraft.HttpApi.Host.csproj --configuration Release
  
  migrate-and-deploy:
    name: Migrate and Deploy
    needs: "build-and-publish"
    runs-on: self-hosted
    steps:
      - name: Migrate and Deploy
        run: |
          Stop-IISSite -Name soft-craft-api -Confirm:$false
          cd ./src/SoftCraft.DbMigrator/bin/Release/net6.0/
          ./SoftCraft.DbMigrator.exe
          cd ../../../../..
          Copy-Item ./src/SoftCraft.HttpApi.Host/bin/Release/net6.0/publish/* C:/inetpub/wwwroot/soft-craft-api -Recurse -Force
          Start-IISSite -Name soft-craft-api
          Remove-Item .\* -Force -Recurse
          
