name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build(Release)
      run: dotnet build --configuration Release --no-restore
    - name: Deploy to IIS
      run: |
        Stop-IISSite -Name soft-craft-api -Confirm:$false
        Copy-Item ./src/SoftCraft.HttpApi.Host/bin/Release/net6.0/* C:/inetpub/wwwroot/soft-craft-api -Recurse -Force
        Start-IISSite -Name soft-craft-api